#!/usr/bin/env bash

set -euo pipefail

SCRIPT_PATH="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/$(basename "${BASH_SOURCE[0]}")"
REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
LOCAL_HOST="127.0.0.1"
LOCAL_PORT="8545"
FORK_BLOCK_NUMBER=""
ENV_FILE="$REPO_ROOT/.society-nft-auction-fork.env"
START_AUCTION=false

usage() {
    printf '%s\n' \
        "Usage: $0 [--port PORT] [--block-number BLOCK] [--env-file PATH] [--start]" \
        "" \
        "Starts a foreground Base-mainnet Anvil fork, deploys and approves the" \
        "Society NFT auction, validates it, and writes public frontend settings." \
        "The fork stops when this process receives Ctrl-C." \
        "" \
        "Options:" \
        "  --port PORT          Local RPC port (default: 8545)" \
        "  --block-number BLOCK Pin the Base fork to a block (default: latest)" \
        "  --env-file PATH      Public runtime output (default: .society-nft-auction-fork.env)" \
        "  --start              Start the local auction after validation"
}

while (($#)); do
    case "$1" in
        --port)
            LOCAL_PORT="${2:?missing value for --port}"
            shift 2
            ;;
        --block-number)
            FORK_BLOCK_NUMBER="${2:?missing value for --block-number}"
            shift 2
            ;;
        --env-file)
            ENV_FILE="${2:?missing value for --env-file}"
            shift 2
            ;;
        --start)
            START_AUCTION=true
            shift
            ;;
        -h | --help)
            usage
            exit 0
            ;;
        *)
            printf 'Unknown argument: %s\n\n' "$1" >&2
            usage >&2
            exit 2
            ;;
    esac
done

cd "$REPO_ROOT"

set -a
# shellcheck disable=SC1091
source config/fame-public.env
set +a

if [[ -z "${RPC_URL:-}" || -z "${DEPLOYER_PRIVATE_KEY:-}" ]]; then
    if [[ "${SOCIETY_FORK_DOPPLER_BOOTSTRAPPED:-}" == "1" ]]; then
        [[ -n "${RPC_URL:-}" ]] || printf 'Missing Doppler prd secret: RPC_URL\n' >&2
        [[ -n "${DEPLOYER_PRIVATE_KEY:-}" ]] || printf 'Missing Doppler prd secret: DEPLOYER_PRIVATE_KEY\n' >&2
        exit 1
    fi
    command -v doppler >/dev/null 2>&1 || {
        printf 'Missing command: doppler\n' >&2
        exit 1
    }
    relaunch_args=(--port "$LOCAL_PORT" --env-file "$ENV_FILE")
    if [[ -n "$FORK_BLOCK_NUMBER" ]]; then
        relaunch_args+=(--block-number "$FORK_BLOCK_NUMBER")
    fi
    if [[ "$START_AUCTION" == true ]]; then
        relaunch_args+=(--start)
    fi
    export SOCIETY_FORK_DOPPLER_BOOTSTRAPPED=1
    exec doppler run --config "${DOPPLER_CONFIG:-prd}" -- "$SCRIPT_PATH" "${relaunch_args[@]}"
fi

for required_command in anvil cast forge; do
    command -v "$required_command" >/dev/null 2>&1 || {
        printf 'Missing command: %s\n' "$required_command" >&2
        exit 1
    }
done

: "${BASE_FAME_NFT_ADDRESS:?missing BASE_FAME_NFT_ADDRESS in config/fame-public.env}"
: "${BASE_SOCIETY_NFT_AUCTION_OWNER:?missing BASE_SOCIETY_NFT_AUCTION_OWNER in config/fame-public.env}"
: "${BASE_SOCIETY_NFT_AUCTION_TOKEN_ID:?missing BASE_SOCIETY_NFT_AUCTION_TOKEN_ID in config/fame-public.env}"

LOCAL_RPC_URL="http://$LOCAL_HOST:$LOCAL_PORT"
GENERATED_ENV_MARKER="# Generated by script/start-society-nft-auction-fork.sh"
if [[ -e "$ENV_FILE" ]] && ! head -n 1 "$ENV_FILE" | grep -Fqx "$GENERATED_ENV_MARKER"; then
    printf 'Refusing to overwrite non-generated environment file: %s\n' "$ENV_FILE" >&2
    exit 1
fi
if cast chain-id --rpc-timeout 1 --rpc-url "$LOCAL_RPC_URL" >/dev/null 2>&1; then
    printf 'Port %s already serves an RPC. Stop it or choose --port.\n' "$LOCAL_PORT" >&2
    exit 1
fi

deployer_address="$(cast wallet address --private-key "$DEPLOYER_PRIVATE_KEY")"
owner_lower="$(printf '%s' "$BASE_SOCIETY_NFT_AUCTION_OWNER" | tr '[:upper:]' '[:lower:]')"

runtime_dir="$(mktemp -d "${TMPDIR:-/tmp}/society-nft-auction-fork.XXXXXX")"
anvil_log="$runtime_dir/anvil.log"
anvil_pid=""
env_file_written=false
ENV_INVOCATION_MARKER="# Invocation: $$"
cleanup() {
    if [[ -n "$anvil_pid" ]]; then
        kill "$anvil_pid" >/dev/null 2>&1 || true
        wait "$anvil_pid" >/dev/null 2>&1 || true
    fi
    if [[ "$env_file_written" == true ]] \
        && [[ -f "$ENV_FILE" ]] \
        && grep -Fqx "$ENV_INVOCATION_MARKER" "$ENV_FILE"; then
        rm -f -- "$ENV_FILE"
    fi
    rm -rf -- "$runtime_dir"
}
trap cleanup EXIT INT TERM

export BASE_RPC="$RPC_URL"
export FOUNDRY_BROADCAST="$runtime_dir/broadcast"
export FOUNDRY_CACHE_PATH="$runtime_dir/cache"

anvil_args=(
    --fork-url base
    --host "$LOCAL_HOST"
    --port "$LOCAL_PORT"
    --chain-id 8453
    --auto-impersonate
    --quiet
)
if [[ -n "$FORK_BLOCK_NUMBER" ]]; then
    anvil_args+=(--fork-block-number "$FORK_BLOCK_NUMBER")
fi

env -i \
    PATH="$PATH" \
    HOME="$HOME" \
    TMPDIR="${TMPDIR:-/tmp}" \
    BASE_RPC="$BASE_RPC" \
    anvil "${anvil_args[@]}" >"$anvil_log" 2>&1 &
anvil_pid=$!

chain_id=""
readiness_deadline=$((SECONDS + 10))
while ((SECONDS < readiness_deadline)); do
    if chain_id="$(cast chain-id --rpc-timeout 1 --rpc-url "$LOCAL_RPC_URL" 2>/dev/null)"; then
        break
    fi
    chain_id=""
    if ! kill -0 "$anvil_pid" >/dev/null 2>&1; then
        printf 'Anvil exited before the local RPC became ready.\n' >&2
        sed -n '1,120p' "$anvil_log" >&2
        exit 1
    fi
    sleep 0.2
done

if [[ -z "$chain_id" ]]; then
    printf 'Anvil did not become ready at %s within 10 seconds.\n' "$LOCAL_RPC_URL" >&2
    sed -n '1,120p' "$anvil_log" >&2
    exit 1
fi
if [[ "$chain_id" != "8453" ]]; then
    printf 'Expected Base chain ID 8453, received %s.\n' "$chain_id" >&2
    exit 1
fi

token_owner="$(cast call "$BASE_FAME_NFT_ADDRESS" 'ownerOf(uint256)(address)' \
    "$BASE_SOCIETY_NFT_AUCTION_TOKEN_ID" --rpc-url "$LOCAL_RPC_URL")"
token_owner_lower="$(printf '%s' "$token_owner" | tr '[:upper:]' '[:lower:]')"
if [[ "$token_owner_lower" != "$owner_lower" ]]; then
    printf 'Token %s is owned by %s at the fork block, expected %s.\n' \
        "$BASE_SOCIETY_NFT_AUCTION_TOKEN_ID" "$token_owner" "$BASE_SOCIETY_NFT_AUCTION_OWNER" >&2
    exit 1
fi

deployment_nonce="$(cast nonce "$deployer_address" --rpc-url "$LOCAL_RPC_URL")"
auction_address="$(cast compute-address "$deployer_address" --nonce "$deployment_nonce" | awk '{print $3}')"

export BASE_DEPLOYER_PRIVATE_KEY="$DEPLOYER_PRIVATE_KEY"
export BASE_RPC="$LOCAL_RPC_URL"
forge script script/DeploySocietyNftAuction.s.sol \
    --chain 8453 \
    --rpc-url "$LOCAL_RPC_URL" \
    --broadcast >/dev/null

if [[ "$(cast code "$auction_address" --rpc-url "$LOCAL_RPC_URL")" == "0x" ]]; then
    printf 'No auction bytecode found at predicted address %s.\n' "$auction_address" >&2
    exit 1
fi

cast send "$BASE_FAME_NFT_ADDRESS" 'approve(address,uint256)' \
    "$auction_address" \
    "$BASE_SOCIETY_NFT_AUCTION_TOKEN_ID" \
    --from "$BASE_SOCIETY_NFT_AUCTION_OWNER" \
    --unlocked \
    --rpc-url "$LOCAL_RPC_URL" >/dev/null

export BASE_SOCIETY_NFT_AUCTION_ADDRESS="$auction_address"
forge script script/ValidateSocietyNftAuctionBase.s.sol \
    --chain 8453 \
    --rpc-url "$LOCAL_RPC_URL" >/dev/null

if [[ "$START_AUCTION" == true ]]; then
    cast send "$auction_address" 'start(uint256)' \
        "$BASE_SOCIETY_NFT_AUCTION_TOKEN_ID" \
        --from "$BASE_SOCIETY_NFT_AUCTION_OWNER" \
        --unlocked \
        --rpc-url "$LOCAL_RPC_URL" >/dev/null
fi

unset RPC_URL DEPLOYER_PRIVATE_KEY ETHERSCAN_API_KEY BASE_RPC BASE_DEPLOYER_PRIVATE_KEY

lifecycle="$(cast call "$auction_address" 'lifecycle()(uint8)' --rpc-url "$LOCAL_RPC_URL")"
fork_block="$(cast block-number --rpc-url "$LOCAL_RPC_URL")"
case "$lifecycle" in
    0) lifecycle_name="Unstarted" ;;
    1) lifecycle_name="Active" ;;
    2) lifecycle_name="Settled" ;;
    *) lifecycle_name="Unknown" ;;
esac

mkdir -p "$(dirname "$ENV_FILE")"
generated_env_file="$runtime_dir/frontend.env"
{
    printf '%s\n' "$GENERATED_ENV_MARKER"
    printf '%s\n' "$ENV_INVOCATION_MARKER"
    printf 'NEXT_PUBLIC_BASE_RPC_URL=%s\n' "$LOCAL_RPC_URL"
    printf 'NEXT_PUBLIC_SOCIETY_NFT_AUCTION_ADDRESS=%s\n' "$auction_address"
    printf 'NEXT_PUBLIC_SOCIETY_NFT_ADDRESS=%s\n' "$BASE_FAME_NFT_ADDRESS"
    printf 'NEXT_PUBLIC_SOCIETY_NFT_AUCTION_TOKEN_ID=%s\n' "$BASE_SOCIETY_NFT_AUCTION_TOKEN_ID"
} >"$generated_env_file"
env_file_written=true
mv "$generated_env_file" "$ENV_FILE"

printf '\nSociety NFT auction fork is ready.\n'
printf 'RPC:       %s\n' "$LOCAL_RPC_URL"
printf 'Chain ID:  %s\n' "$chain_id"
printf 'Fork block: %s\n' "$fork_block"
printf 'Auction:   %s\n' "$auction_address"
printf 'Token:     %s\n' "$BASE_SOCIETY_NFT_AUCTION_TOKEN_ID"
printf 'Lifecycle: %s (%s)\n' "$lifecycle" "$lifecycle_name"
printf 'Frontend:  %s\n' "$ENV_FILE"
printf '\nKeep this terminal open. Press Ctrl-C to stop the fork.\n'

wait "$anvil_pid"
